### ISSUE TITLE
Context deadline exceeded at start locally

### ISSUE THREAD

**Issue by losnappas** [aws/aws-lambda-go#361]
I'm running the lambda image locally, and long story short, it starts off with an expired context deadline.

```golang
package main

import (
	"context"
	"log"

	"github.com/aws/aws-lambda-go/lambda"
)

func Handler(ctx context.Context) {
	log.Println(ctx.Err())
	log.Println(ctx.Deadline())
}
func main() {
	lambda.Start(Handler)
}
```

```dockerfile
# installer
FROM golang:1.15-alpine3.12@sha256:4d8abd16b03209b30b48f69a2e10347aacf7ce65d8f9f685e8c3e20a512234d9 as installer
WORKDIR /build

COPY ./go.mod ./go.sum ./

RUN go mod download

# builder
FROM installer as builder

COPY . ./

RUN CGO_ENABLED=0 GOOS=linux go build -o Main ./main.go

# release
FROM public.ecr.aws/lambda/go:latest

COPY --from=builder /build/Main .

CMD ["./Main"]
```

`curl localhost:8080/2015-03-31/functions/function/invocations`

logs

```
time="2021-02-27T23:20:12.39" level=info msg="exec '/var/runtime/bootstrap' (cwd=/var/task, handler=)"
time="2021-02-27T23:20:48.623" level=info msg="extensionsDisabledByLayer(/opt/disable-extensions-jwigqn8j) -> stat /opt/disable-extensions-jwigqn8j: no such file or directory"
time="2021-02-27T23:20:48.624" level=warning msg="Cannot list external agents" error="open /opt/extensions: no such file or directory"
START RequestId: 9af7aefe-d612-4f5e-9e75-c9cdeadab9f5 Version: $LATEST
2021/02/27 23:20:48 context deadline exceeded
2021/02/27 23:20:48 2021-02-27 23:20:48.631152628 +0000 UTC true
END RequestId: 9af7aefe-d612-4f5e-9e75-c9cdeadab9f5
REPORT RequestId: 9af7aefe-d612-4f5e-9e75-c9cdeadab9f5  Init Duration: 0.20 ms  Duration: 7.73 ms       Billed Duration: 100 ms        Memory Size: 3008 MB    Max Memory Used: 3008 MB
```

"context deadline exceeded"

What am I missing? [Here](https://docs.aws.amazon.com/lambda/latest/dg/golang-context.html) it says

> Context methods
    Deadline – Returns the date that the execution times out, in Unix time milliseconds.

But it's essentially returning the starting time instead.

**Comment by JadenSimon** [comment]
I'm having this issue as well using SAM CLI. Is there some sort of parameter or environment variable that needs to be set for the context deadline?

**Comment by drewsymo** [comment]
Can confirm I'm also having this issue when calling Dynamo with the Lambda context:

```
	_, err = ddb.PutItemWithContext(ctx, &piu) // Deadline exceeded..
```

**Comment by annymosse** [comment]
i have same issue :
### to produce the problem:
```bash
amplify add function testFunc
```

then choose `go` with default config ,then:
```
amplify mock function testFunc
```

the output:
```
? Provide the path to the event JSON object relative to ..../amplify/backend/function/testFunc src/event.json
Ensuring latest function changes are built...
Starting execution...
Local invoker binary was not found, building it...
go: github.com/aws/aws-lambda-go@v1.15.0: missing go.sum entry; to add it:
        go mod download github.com/aws/aws-lambda-go
testFunc failed with the following error:
Error: Command failed with exit code 1: go build main.go
    at makeError (/home/me/.config/yarn/global/node_modules/execa/lib/error.js:59:11)
    at Function.module.exports.sync (/home/me/.config/yarn/global/node_modules/execa/index.js:188:17)
    at Object.executeCommand (/home/me/.config/yarn/global/node_modules/amplify-go-function-runtime-provider/src/runtime.ts:31:24)
    at buildLocalInvoker (/home/me/.config/yarn/global/node_modules/amplify-go-function-runtime-provider/src/localinvoke.ts:29:5)
    at Object.localInvoke (/home/me/.config/yarn/global/node_modules/amplify-go-function-runtime-provider/src/localinvoke.ts:67:30)
    at Object.invoke (/home/me/.config/yarn/global/node_modules/amplify-go-function-runtime-provider/src/index.ts:26:24)
    at /home/me/.config/yarn/global/node_modules/amplify-category-function/src/index.ts:185:20
    at Object.start (/home/me/.config/yarn/global/node_modules/amplify-util-mock/src/func/index.ts:48:49)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at Object.run (/home/me/.config/yarn/global/node_modules/amplify-util-mock/src/commands/mock/function.ts:14:5)
    at Object.executeAmplifyCommand (/home/me/.config/yarn/global/node_modules/amplify-util-mock/src/amplify-plugin-index.ts:8:3)
    at executePluginModuleCommand (/home/me/.config/yarn/global/node_modules/@aws-amplify/cli/src/execution-manager.ts:175:3)
    at Object.executeCommand (/home/me/.config/yarn/global/node_modules/@aws-amplify/cli/src/execution-manager.ts:28:5)
    at Object.run (/home/me/.config/yarn/global/node_modules/@aws-amplify/cli/src/index.ts:139:5) {
  shortMessage: 'Command failed with exit code 1: go build main.go',
  command: 'go build main.go',
  exitCode: 1,
  signal: undefined,
  signalDescription: undefined,
  stdout: undefined,
  stderr: undefined,
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false
}
Finished execution.
```

whenever i built the same function and others functions and tested them using Dockerfile:
```Dockerfile
FROM amazon/aws-lambda-go:latest

COPY main ${LAMBDA_TASK_ROOT}

CMD [ "main" ]
```
and trigger it by curl:
```
curl -XPOST "http://localhost:9000/2015-03-31/functions/function/invocations" -d '{"payload":"world"}'
>hello world!
```
**Note** there's no issue when using `nodejs`.

**Comment by EltonGarcia** [comment]
Still facing the issue with SAM CLI version 1.25.0 on Ubuntu. Any workarounds for that?

**Comment by andrew-yustyk** [comment]
SAM CLI, version 1.26.0
The same issue on Ubuntu

**Comment by robin-sanner** [comment]
Same issue on MacOS SAM CLI, version 1.29.0

**Comment by zkhan96** [comment]
Same issue on MacOS SAM CLI, version 1.29.0

**Comment by arianvp** [comment]
Could it be that  SAM doesn't set the deadline header?

I think the bug is in the following line:
https://github.com/aws/aws-lambda-go/blob/8e674dad171cebefc4819d785251a76334827bb2/lambda/invoke_loop.go#L133

If the header isn't present, deadline is `0` which causes the context to be immediately cancelled.

We should instead not call `WithDeadline` at all if the header isn't present:
https://github.com/aws/aws-lambda-go/blob/8e674dad171cebefc4819d785251a76334827bb2/lambda/invoke_loop.go#L52
