### ISSUE TITLE
Issue: missing go.sum entry; to add it: go mod download github.com/aws/aws-lambda-go

### ISSUE THREAD

**Issue by annymosse** [aws/aws-lambda-go#384]
**Is your feature request related to a problem? Please describe.**
I cant test amplify locally using aws-lambda-go , it say `missing go.sum entry; to add it: go mod download github.com/aws/aws-lambda-go` whenever i have installed `aws-lambda-go` and there's no problem when i build it locally or using docker container.

**Additional context**
to produce the problem:
```bash
amplify add function testFunc
```

then choose `go` with default config ,then:
```
amplify mock function testFunc
```

the output:
```
? Provide the path to the event JSON object relative to ..../amplify/backend/function/testFunc src/event.json
Ensuring latest function changes are built...
Starting execution...
Local invoker binary was not found, building it...
go: github.com/aws/aws-lambda-go@v1.15.0: missing go.sum entry; to add it:
        go mod download github.com/aws/aws-lambda-go
testFunc failed with the following error:
Error: Command failed with exit code 1: go build main.go
    at makeError (/home/me/.config/yarn/global/node_modules/execa/lib/error.js:59:11)
    at Function.module.exports.sync (/home/me/.config/yarn/global/node_modules/execa/index.js:188:17)
    at Object.executeCommand (/home/me/.config/yarn/global/node_modules/amplify-go-function-runtime-provider/src/runtime.ts:31:24)
    at buildLocalInvoker (/home/me/.config/yarn/global/node_modules/amplify-go-function-runtime-provider/src/localinvoke.ts:29:5)
    at Object.localInvoke (/home/me/.config/yarn/global/node_modules/amplify-go-function-runtime-provider/src/localinvoke.ts:67:30)
    at Object.invoke (/home/me/.config/yarn/global/node_modules/amplify-go-function-runtime-provider/src/index.ts:26:24)
    at /home/me/.config/yarn/global/node_modules/amplify-category-function/src/index.ts:185:20
    at Object.start (/home/me/.config/yarn/global/node_modules/amplify-util-mock/src/func/index.ts:48:49)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at Object.run (/home/me/.config/yarn/global/node_modules/amplify-util-mock/src/commands/mock/function.ts:14:5)
    at Object.executeAmplifyCommand (/home/me/.config/yarn/global/node_modules/amplify-util-mock/src/amplify-plugin-index.ts:8:3)
    at executePluginModuleCommand (/home/me/.config/yarn/global/node_modules/@aws-amplify/cli/src/execution-manager.ts:175:3)
    at Object.executeCommand (/home/me/.config/yarn/global/node_modules/@aws-amplify/cli/src/execution-manager.ts:28:5)
    at Object.run (/home/me/.config/yarn/global/node_modules/@aws-amplify/cli/src/index.ts:139:5) {
  shortMessage: 'Command failed with exit code 1: go build main.go',
  command: 'go build main.go',
  exitCode: 1,
  signal: undefined,
  signalDescription: undefined,
  stdout: undefined,
  stderr: undefined,
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false
}
Finished execution.
```

whenever i built the same function and others functions and tested them using Dockerfile:
```Dockerfile
FROM amazon/aws-lambda-go:latest

COPY main ${LAMBDA_TASK_ROOT}

CMD [ "main" ]
```
and trigger it by curl:
```
curl -XPOST "http://localhost:9000/2015-03-31/functions/function/invocations" -d '{"payload":"world"}'
>hello world!
```
**Note** there's no issue when using `nodejs`.

And i had mentioned this issue already in a wrong location [Context deadline exceeded at start locally](https://github.com/aws/aws-lambda-go/issues/361).

**Comment by bmoffatt** [comment]
This project's issues isn't the best place to debug issues with Amplify's tooling. As you've pointed out, things appear to work for you in Docker, and on your local machine. If you're stilling having an issue with this, you might try https://github.com/aws-amplify/amplify-cli or https://repost.aws/
